### ISSUE TITLE
Expose `ref` property

### ISSUE THREAD

**Issue by iget-master** [goveo/react-international-phone#104]
**Is your feature request related to a problem? Please describe.**

I'm trying to use this component with Informed (https://github.com/teslamotors/informed), but it needs to set the `ref` for the input element in order to work.

Since this component uses ref for it internal purposes, it just ignores the ref property.

**Describe the solution you'd like**

The component should check if the `ref` is passed as prop, and if it is, use it instead of creating a new one.

**Describe alternatives you've considered**

None

**Additional context**

**Comment by goveo** [comment]
@iget-master Ref forwarding is added to v4.0.0.
You can check docs for it here:
https://react-international-phone.vercel.app/docs/Usage/PhoneInput#ref-forwarding

I will close this issue, feel free to reopen it if anything is wrong.
