### ISSUE TITLE
Preferred Countries

### ISSUE THREAD

**Issue by onlywei** [goveo/react-international-phone#137]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Other libraries such as https://patw0929.github.io/react-intl-tel-input/ have a `preferredCountries` prop that can be used to group a set of preferred countries at the top of the list.

This is just a prop of the form:
```
preferredCountries={['us', 'gb']}
```

**Describe alternatives you've considered**
Filtering the countries makes the non-preferred countries go away. I would much rather still show all countries, but have preferred countries show at the top like the other libraries.

**Additional context**
If given `preferredCountries={['us', 'gb']}`, the phone input will render like this:
![image](https://github.com/goveo/react-international-phone/assets/1470998/cc9890a7-f341-4228-9f2e-fe7d3feb3973)

**Comment by raphaelbadia** [comment]
Thanks for this feature !

**Comment by AmandineTournay** [comment]
Hello,
Thank you very much for that feature !

I am using the version `4.2.1`, and unfortunately I see that it is partially working either on the Storybook and my project on **Firefox** only. (Chrome and Edge are working perfectly, and I do not know for Safari as I do not have any Apple device)

The divider is showing well depending on the size of the `preferredCountries` list, but the list is not refreshed.

![image](https://github.com/goveo/react-international-phone/assets/144104311/f8decc9c-be7d-4d77-abd1-3b7c99ad3bad)
