### ISSUE TITLE
Expose types from the root

### ISSUE THREAD

**Issue by oleseaciumac** [goveo/react-international-phone#157]
Problem:
I tried to import ParsedCountry type and it worked well on my machine, however it broke build on deployment, because by that time there was already a new version release with the 'build' folder renamed into 'dist'.

**Describe the solution you'd like**
Ideally types should be to be exposed from the root folder

**Comment by goveo** [comment]
@oleseaciumac Types export is updated in v4.2.5.
Please check that all the types you need are exported from root. Feel free reopen this ticket if anything is missing 🙏
