### ISSUE TITLE
Canada flag changes to USA when filling input

### ISSUE THREAD

**Issue by esau-morais** [goveo/react-international-phone#165]
**Describe the bug**
Canada flag changes to USA when filling input

**To Reproduce**

1. Go to main page
2. Choose canada flag
3. Enter a phone number
4. Notice that the country flag changes to USA

**Expected behavior**
Country flag should stay the same

**Desktop (please complete the following information):**

- OS: Windows
- Browser Firefox
- Version 123

**Comment by esau-morais** [comment]
I noticed that this happens because it doesn't start one one of the numbers in the array provided to the [`countryData`](https://github.com/goveo/react-international-phone/blob/master/src/data/countryData.ts#L69-L112)

**Comment by salamatsu** [comment]
![image](https://github.com/goveo/react-international-phone/assets/81408592/c467466f-121c-4914-ad81-b1d07e6c1b4a)

i tried valid Canadian number
