### ISSUE TITLE
Change the Country Flag and Code to some other Actions

### ISSUE THREAD

**Issue by huzaifaQas** [goveo/react-international-phone#176]
I have a scenerio in which i am changing the country depending on the user timeZone Selection...
but it is not change the update the country meta according to country code

import React ,{useState} from 'react';
import countryiso from "countries-and-timezones";
import { PhoneInput } from "react-international-phone";
import "react-international-phone/style.css";
import {
  Form,
  Input,
  Select
} from "antd";

function App() {
  let getUsertimeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const countriesList = countryiso.getAllCountries();
  const countryKeys = Object.keys(countriesList);
  let country = null;
  for (let key of countryKeys) {
      if (countriesList[key].timezones.includes(getUsertimeZone)) {
          country = countriesList[key].id;
          break;
      }
  }
  const timeZonesList = Intl.supportedValuesOf('timeZone');
  let timeZones = [];
  for (let i = 0; i < timeZonesList.length; i++) {
    timeZones[i] = { value: timeZonesList[i], label: timeZonesList[i] };
  }
  const getIndex = timeZones.findIndex(
    (item) => item.value === getUsertimeZone
  );
  const[countryCode,setCountryCode]=useState(country)
  const [phone,setPhone]=useState()
  const ChangeTimeZone = (e) =>{
    let country=null
    for (let key of countryKeys) {
      if (countriesList[key].timezones.includes(e)) {
          country= countriesList[key].id;
          break;
      }
    }
    setCountryCode(country)
  }
  return (
    <div className="App">
      <Form initialValues={{ timeZone: timeZones[getIndex].value }}>
        <Form.Item
          name="timeZone"
        >
          <Select
                className="someClass"
                placeholder="Timezone"
                showSearch
                optionFilterProp="children"
                onChange= {(e)=>{
                  ChangeTimeZone(e);
                }}
                filterOption={(input, option) =>
                  option.children.toLowerCase().includes(input.toLowerCase())
                }
              >
                {timeZonesList.map((item) => {
                  return <Option value={item}>{item}</Option>;
                })}
              </Select>
        </Form.Item>
      </Form>
      <PhoneInput
                  className="input"
                  defaultCountry={`${countryCode.toLowerCase()}`}
                  value={phone}
                  onChange={(phone) => setPhone(phone)}
                  placeholder="Phone Number"
      />
    </div>
  );
}

export default App;

**Comment by goveo** [comment]
@huzaifaQas You should use the `ref.setCountry` if you want to update the country dynamically.

Basic example:
```jsx
const ref = useRef(null);

const onSomeAction = () => {
  ref.setCountry('us');
}

return (
  <PhoneInput ref={ref}>;
)
```

Checkout docs:
https://react-international-phone.vercel.app/docs/Usage/PhoneInput#ref-forwarding
