### ISSUE TITLE
How to clear input on initial render?

### ISSUE THREAD

**Issue by BrilliantDecision** [goveo/react-international-phone#178]
When input mounts, we see country code, for example +1. But I want to have an empty input on initial render
We can clear input with ref, but hook stores the initial value until you use handlePhoneValueChange method

**Comment by goveo** [comment]
@BrilliantDecision Use the `disableDialCodePrefill` prop
https://react-international-phone.vercel.app/docs/Usage/PhoneInput#disabledialcodeprefill
