### ISSUE TITLE
React 19 Support

### ISSUE THREAD

**Issue by AnalyteSoftware** [goveo/react-international-phone#222]
When launching "npm i" to install all packages from my next.js project. I get the following error when using the new stable react 19 and next.js 15.1.0.

Could not resolve dependency:
npm error peer react@"^16.8.0 || ^17.0.0 || ^18.0.0" from react-international-phone@4.3.0

When is react 19 support expected to be available?

**Comment by goveo** [comment]
@AnalyteSoftware I'm working on the fix right now.
You can also try to install it with `--force` or `--legacy-peer-deps` flag if you need it ASAP (there should not be any breaking changes)

**Comment by goveo** [comment]
React 19 support is added in version 4.4.0
