### ISSUE TITLE
node combability issues with build pipelines

### ISSUE THREAD

**Issue by onlyreddy** [goveo/react-international-phone#31]
Hi,

Thanks for creating the package it helped me a lot. I'm facing issues with the node version in my build pipeline. In the package, you have used 16. x.

![image](https://user-images.githubusercontent.com/16205943/220591251-730cf219-0a17-4900-9543-f897e41dfd5c.png)

While I'm using 18. x of the @types/node version. I tried to downgrade the version to 16. x in my local. However, it's not working the build pipelines.

Below is the error.
![image](https://user-images.githubusercontent.com/16205943/220591915-ab77c009-e4c6-4985-959a-8e32fb15d1f2.png)

Do you definitely need that version? Can you please help me to fix it?

**Comment by goveo** [comment]
@onlyreddy Hey, update to [v1.8.6](https://github.com/goveo/react-international-phone/releases/tag/v1.8.6) please, it should be fixed now

**Comment by I-Atlas** [comment]
@goveo Thank you very much!

**Comment by onlyreddy** [comment]
@goveo It's worked for me and thanks for the quick fix.

**Comment by goveo** [comment]
🎉 Thank you for your effort!
⭐ Consider leaving a star on this repo if you like the project.
