### ISSUE TITLE
Jest error when trying to test a component that uses the lib

### ISSUE THREAD

**Issue by lucasluca** [goveo/react-international-phone#34]
**Describe the bug**
Jest error when trying to test a component that uses the lib

**To Reproduce**
* Try to test a component that uses the lib

**Expected behavior**
Pass the tests 

**Screenshots**
![image](https://user-images.githubusercontent.com/16627838/221441483-4d809d3c-5215-459d-8de6-35ea2e4308b1.png)

**Additional context**
Jest version

"jest": "^29.1.2",
 "jest-environment-jsdom": "^29.1.2",

**Comment by goveo** [comment]
Hey, @lucasluca
Seems like your Jest environment is not configured to handle css modules correctly.
Check this workaround for quick fix: https://stackoverflow.com/a/43813992
Or check the Jest docs article about [Mocking CSS Modules](https://jestjs.io/docs/webpack#mocking-css-modules).
Reply here please if it helps 🙏

**Comment by lucasluca** [comment]
Thanks @goveo it worked with this solution
![image](https://user-images.githubusercontent.com/16627838/221443643-1fb9a5c7-f36b-452d-9bd0-5cc4cc63cdab.png)

**Comment by goveo** [comment]
🎉 Thank you for your effort!
⭐ Consider leaving a star on this repo if you like the project.
