### ISSUE TITLE
About Chinese mobile phone number template

### ISSUE THREAD

**Issue by Baoing** [goveo/react-international-phone#35]
Your plug-in is very good, but it is a little unfriendly to Chinese users. The format of Chinese mobile phone number is +86 xxxxxxx xxxx, and the format of the plug-in is +86 xx-xxxxxxxxx. Can you support the template format of Chinese mobile phone number

Or can you show me how to do it to achieve what I want，Thank you~

![image](https://user-images.githubusercontent.com/56350557/222868164-455a30f0-068d-49f5-b935-2cba65dd99ff.png)

![image](https://user-images.githubusercontent.com/56350557/222868196-43e4882b-c8a0-4494-82f1-5eda50f80c3b.png)

**Comment by Baoing** [comment]
![image](https://user-images.githubusercontent.com/56350557/222869831-1bda2cdf-b6dc-4b5b-998d-3d284c558cfb.png)
I could solve my problem this way, but I think this is obviously not the best solution, and it would be better to provide a local phone template change

**Comment by goveo** [comment]
@Baoing
Chinese format mask changed to `... .... ....` in [v1.8.8](https://github.com/goveo/react-international-phone/releases/tag/v1.8.8)
🎉 Thank you for your effort!
