### ISSUE TITLE
Returning E164 format string value when using usePhoneInput hook with own UI input

### ISSUE THREAD

**Issue by rahulkeerthi** [goveo/react-international-phone#37]
Hi, thanks for this great library -- it's easy to implement with existing input components (material ui v4), so that's the approach I'm taking with the usePhoneInput hook. 

The challenge I have is how to ensure that the phone number string value returned is in E164 format (e.g. +447810182855) rather than the formatted value that the component returns (e.g. `+447810 182855` with `hideSpaceAfterDialCode: true`, or `+44 7810 182855` with default configuration). The number is always formatted, but I would like to save the E164 format value regardless of what the component renders.

Given that the hook returns a `phone` string that is formatted correctly for the input, can there be an option for the `handlePhoneValueChange` function to (also) return an unformatted / E164 format value? 

**Describe alternatives you've considered**
I've applied a replace to the string before saving `newValue.replace(/[^+0-9]/g, '')` but this causes issues with the cursor placement, so I've had to force that to the end with `metadata.cursorPosition = unformattedValue.length` in the `onPhoneUpdate` function. This is not ideal, so I would like the ability to manage a E164 format string value and the formatted value separately.

**Comment by goveo** [comment]
Hey @rahulkeerthi.
As I understand you want to display and save phones as E164, right?

If so, you can modify format masks for your countries like that:
```ts
const countries = defaultCountries.map((country) => {
  const parsedCountry = parseCountry(country);
  return buildCountryData({
    ...parsedCountry,
    format: parsedCountry.format?.replace(/[^\\.]*/g, ""), // remove all except dots
  });
});
```
and pass it to `usePhoneInput` with `hideSpaceAfterDialCode: true`

**Comment by rahulkeerthi** [comment]
Hi @goveo, thanks for the quick input! I would like to display the number as formatted and save as E164, I imagine this is the ideal use case for this library as E164 is a standard format and therefore most flexible for saving. Returning the string in a formatted way doesn't seem like a sensible default, unless I am misunderstanding the E164 standard and/or the role of this hook/input component. 

If there's no other way than what you propose, I don't mind losing the benefit of a formatted display for now, but I think this would be a great enhancement to have.

I have a hook that takes care of the country and default country settings for `usePhoneInput` so with your proposed change it looks like this:

```
import { isNil } from 'lodash'
import {
  type CountryIso2,
  defaultCountries,
  parseCountry,
  buildCountryData,
} from 'react-international-phone'
import { type CountryData } from 'react-international-phone/build/types'

const FALLBACK_COUNTRY_ISO = 'us'

interface UseCountryIsoHook {
  getInitialCountry: (defaultCountry: CountryIso2 | undefined) => CountryIso2
  getCountriesList: (
    fixedCountryConfig: Array<CountryIso2> | CountryIso2 | undefined,
  ) => Array<CountryData>
}

export const useCountryIso = (): UseCountryIsoHook => {
  /**
   * This function will return the country iso2 code to use for the input select,
   * based on the defaultCountry prop and the client's browser language (if a valid
   * country iso2 code can be parsed from it), otherwise it will return the fallback
   * @param defaultCountry the default country to use if configured for the question
   * @returns the country iso2 code to use for the input select
   */
  const getInitialCountry = (
    defaultCountry: CountryIso2 | undefined,
  ): CountryIso2 => {
    if (!isNil(defaultCountry)) {
      return defaultCountry
    }
    const clientCountryIso2Value = navigator.language
      .split('-')[1]
      .toLocaleLowerCase() as CountryIso2
    const isValidClientCountryIso2Value = defaultCountries
      .map(c => c[2])
      .includes(clientCountryIso2Value)

    return isValidClientCountryIso2Value
      ? clientCountryIso2Value
      : FALLBACK_COUNTRY_ISO
  }

  /**
   * This function will return the list of countries to use for the input select,
   * based on the fixedCountryConfig prop, otherwise it will return the default list
   * @param fixedCountryConfig the fixed country to use if configured for the question
   * @returns the list of countries to use for the input select
   * @returns the country iso2 code to use for the input select
   */
  const getCountriesList = (
    fixedCountryConfig: Array<CountryIso2> | CountryIso2 | undefined,
  ): Array<CountryData> => {
    if (!isNil(fixedCountryConfig)) {
      if (Array.isArray(fixedCountryConfig)) {
        return defaultCountries.filter(c =>
          fixedCountryConfig.map(c => c.toLowerCase()).includes(c[2]),
        )
      }
      return defaultCountries.filter(
        c => c[2] === fixedCountryConfig.toLowerCase(),
      )
    }
    // remove all other characters from the format to return E164 format
    return defaultCountries.map(country => {
      const parsedCountry = parseCountry(country)
      if (isNil(parsedCountry.format)) return country
      return buildCountryData({
        ...parsedCountry,
        format: parsedCountry.format?.replace(/[^0-9+]/g, ''), // remove all except dots
      })
    })
  }

  return {
    getInitialCountry,
    getCountriesList,
  }
}
```

And of course, thank you for creating this -- really appreciate the effort that has gone into it!

**Comment by rahulkeerthi** [comment]
Update: 

With the config above, I noticed at least one country that doesn't work. An example is Dominican Republic (+1) -- when I start typing +1 the input no longer accepts any values. This might be a conflict with the country guessing logic since the US shares the same post code. It works fine in the demo so not an issue with the vanilla logic.

**Comment by goveo** [comment]
It seems like because you use `isNil` if the following line:
```
if (isNil(parsedCountry.format)) return country
```

Change it to just
```
if (parsedCountry.format) return country
```
and it should be fixed.

It happens because of a bug inside `buildCountryData` which will be fixed in the next releases

**Comment by goveo** [comment]
Thanks for the feedback! 
I will investigate possible ways to add native support for the E164 format.

**Comment by rahulkeerthi** [comment]
> It seems like to happen because you use `isNil` if the following line:
> 
> ```
> if (isNil(parsedCountry.format)) return country
> ```
> 
> Change it to just
> 
> ```
> if (parsedCountry.format) return country
> ```
> 
> and it should be fixed.
> 
> It happens because of a bug inside `buildCountryData` which will be fixed in the next releases

Just to clarify -- `isNil(parsedCountry.format)` is equivalent to the code you provided as example `!parsedCountry.format` so your suggestion actually goes against your original provided code but no worries! I understand there is a bug, so appreciate you will consider all this when you fix it. Thanks again for your help!

**Comment by goveo** [comment]
Oh, sorry, you are right, I meant that
```
if (!parsedCountry.format) return country;
```

We should not handle empty strings as well as `undefined` here. Removing `isNil` should help
