### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'iso2')

### ISSUE THREAD

**Issue by jonaed1230** [goveo/react-international-phone#44]
Just installed and inported the PhoneInput in my nextJS 13 project and it's showing this error.

TypeError: Cannot read properties of undefined (reading 'iso2')

**Comment by goveo** [comment]
Hey @jonaed1230
Can you show a code snippet of how you integrated PhoneInput into your project?
Seems like you forgot to set the `defaultCountry` prop.

```jsx
<PhoneInput defaultCountry="ua" value={phone} onChange={setPhone} />
```

Read more:
https://react-international-phone-docs.vercel.app/docs/Usage/PhoneInput

**Comment by goveo** [comment]
@jonaed1230 After the [v2.1.0](https://github.com/goveo/react-international-phone/releases/tag/v2.1.0) release, `defaultCountry` is not a required property, you can just update the package now.
Please reply here if it helps 🙏

**Comment by jonaed1230** [comment]
Yeah. It's working now. Thanks.
