### ISSUE TITLE
Australian phone number validations

### ISSUE THREAD

**Issue by beardsleym** [goveo/react-international-phone#48]
**Describe the bug**
Australian phone numbers do not pass validation.

**To Reproduce**

- Visit - https://react-international-phone-docs.vercel.app/docs/Usage/PhoneValidation
- Enter;
    -  +61 491 570 159 (mobile)
    -  +61 2 5550 4321 (landline)

![Screenshot 2023-04-21 at 12 19 08 PM](https://user-images.githubusercontent.com/6046506/233697050-7ff7ede2-4bd6-4512-8ff1-05168b7bbffe.png)

**Expected behavior**
- The above should pass validation and the submit button should be enabled.

**Additional context**
- Valid Australian phone numbers [Australian Government Style Guide](https://www.stylemanual.gov.au/grammar-punctuation-and-conventions/numbers-and-measurements/telephone-numbers)

> 02 5550 4321 [A landline number in NSW or the ACT]
> 0491 570 159 [An Australian mobile number]
> 1300 975 707 [An Australia-wide local-rate number]
> 13 00 00 [An alternative Australia-wide local-rate number]
> 1800 160 401 [An Australia-wide freephone number]
> +61 2 5550 4321 [An Australian landline number in international format]
> +61 491 570 159 [An Australian mobile number in international format]

**Comment by goveo** [comment]
Hey @beardsleym
The formatting mask for Australia is `'(..) .... ....'` right now (one digit seems to be redundant).
Seems like it should be changed to `... ... ...` so all phones will be formatted as `+61 000 000 000`.
What do you think?

**Comment by beardsleym** [comment]
Yeh, I looked in the mask and wasn't sure if you could conditionally do it?
Basically only a mobile number will be 04 area code andeverything else is a landline, so could you do something like...

 // Check if the phone number starts with '4'
    if (phoneNumber.startsWith('+614')) {
      // Format the phone number as +61 4xx xxx xxx
      return ... ... ...
    } else {
      // Format the phone number as +61 x xxxx xxxx
      . .... ....
    }

**Comment by goveo** [comment]
I prefer to keep a single mask per country for now.
Maybe it makes more sense to make a mask `. .... ....` (if `... ... ...` is used only when the area code is 4)? 🤔

**Comment by beardsleym** [comment]
Yes, this `. .... ....` I think would be the better format

**Comment by goveo** [comment]
@beardsleym Format mask for Australia should be fixed in [v2.2.1](https://github.com/goveo/react-international-phone/releases/tag/v2.2.1).
Thank you for your effort! ⭐ Consider leaving a star on this repo if you like the project.
