### ISSUE TITLE
Missing params from the handlePhoneValueChange with usePhoneInput

### ISSUE THREAD

**Issue by onlyreddy** [goveo/react-international-phone#49]
Hi @goveo,

Thanks for fixing the **country code clash for the Russia and Kazakhstan #46** issue. I saw the latest migration and it's working if I go with the below way.

![image](https://user-images.githubusercontent.com/16205943/233762029-647d4267-a71e-40c2-8c93-0f149191c2b5.png)

But I'm using it with an MUI library and implemented using the demo that you added in the docs. In that, we are relying on the `usePhoneInput` hook. The `onChange` event from the text field is passed to the `handlePhoneValueChange` method and it'll return a string that is entered in the text field. In this way the country value is reset and the validation is failing again.

It would be very helpful if you can provide the same way of returning two params as phone and country to the hook also. It's kind of an urgent fix for me.

![bitmoji](https://sdk.bitmoji.com/render/panel/4d41e1cd-fd91-4965-ab48-6b6bc2959d6a-0c148428-2235-4dff-8dbd-407f15f6ce39-v1.png?transparent=1&palette=1&width=246)

**Comment by goveo** [comment]
I think you can use `country` field that's returned from `usePhoneInput` hook for it.

```
const { country } =
    usePhoneInput({
    });
```

**Comment by goveo** [comment]
@onlyreddy `onChange` callback that you can pass to the `usePhoneInput` returns phone and country as well.
Checkout this sandbox, that provides a validation for Material UI based input:
https://codesandbox.io/s/react-international-phone-material-ui-185zd1?file=/src/components/MuiPhone.tsx:695-765

```tsx
const { /* some data */ } = usePhoneInput({
  // ...
  onChange: (data) => {
    onChange(data.phone, data.country);
  }
});
```

Also, validation is not required a country param, `isValid` should show the correct value if the phone is filled.
Country can be parsed not right in some cases, but `isValid` should be accurate.

[Docs reference](https://react-international-phone-docs.vercel.app/docs/Advanced%20Usage/usePhoneInput).

Reply here if it helps 🙏

**Comment by onlyreddy** [comment]
It's worked!!

![bitmoji](https://sdk.bitmoji.com/render/panel/36d7a620-944e-44f8-abed-fe8f3b76d48a-0c148428-2235-4dff-8dbd-407f15f6ce39-v1.png?transparent=1&palette=1&width=246)
