### ISSUE TITLE
all flags are refueled at once

### ISSUE THREAD

**Issue by sergeydymovich** [goveo/react-international-phone#60]
after returning to the page with phone input, all flags are requested at once

**Comment by goveo** [comment]
@sergeydymovich Please specify which OS and browser are you using

**Comment by sergeydymovich** [comment]
> @sergeydymovich Please specify which OS and browser you are using

Windows 10 Pro, Google Chrome
update, this problem only exists when devtools is open
maybe it's not a problem :)

**Comment by sergeydymovich** [comment]
@goveo 
Windows 10 Pro, Google Chrome
Update, this problem only exists when devtools is open.
Maybe it's not a problem :)

**Comment by goveo** [comment]
Can't reproduce it. When I reload a page I see that all flags are cached. If I reload the page using ctrl+shift+r (reload and ignore cache) I don't see a list of all flags in a network tab (only visible flags are loaded).

Anyway, thank you for your contribution! ⭐ Consider leaving a star on this repo if you like the project.
