### ISSUE TITLE
Unable to increase width

### ISSUE THREAD

**Issue by GauravDagar11** [goveo/react-international-phone#66]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by goveo** [comment]
You can use the `inputStyle` to update the width of the input:
```tsx
<PhoneInput
  defaultCountry="ua"
  inputStyle={{
    width: '100%',
  }}
/>
```

Example result: 
![image](https://github.com/goveo/react-international-phone/assets/25800848/e3e36e12-2a06-4b5b-8b14-2561a23d14f2)

Docs reference:
https://react-international-phone-docs.vercel.app/docs/Usage/PhoneInput#style-properties

**Comment by goveo** [comment]
@GauravDagar11 Feel free to reply here if it didn't help.

⭐ Consider leaving a star on this repo if you like the project. Thanks!
