### ISSUE TITLE
onChange callback is triggering at the time of loading

### ISSUE THREAD

**Issue by onlyreddy** [goveo/react-international-phone#68]
Hi,

I'm using the Phone component in my project and observed one issue related to it. 

The `onChange `is called at the time of component loading. Ideally, it should call if there is a change in the country or phone value.

Created a Code sandbox [demo](https://codesandbox.io/s/nervous-dust-jcpg8m?file=/src/Form.tsx) to reproduce the fix.

Can you please help me to fix it?

**Comment by goveo** [comment]
Hi @onlyreddy 
In your case `onChange` is called because you passed an empty string to the `value` prop.
You can change the initial value for `phoneNumber` to `"+1 "`:
```ts
// before:
const [phoneNumber, setPhoneNumber] = React.useState<string>("");

// after:
const [phoneNumber, setPhoneNumber] = React.useState<string>("+1 ");
```

**Comment by onlyreddy** [comment]
It's worked for me.

![bitmoji](https://sdk.bitmoji.com/render/panel/4d41e1cd-fd91-4965-ab48-6b6bc2959d6a-0c148428-2235-4dff-8dbd-407f15f6ce39-v1.png?transparent=1&palette=1&width=246)
