### ISSUE TITLE
Can't set value on PhoneInput ??

### ISSUE THREAD

**Issue by sadiki-o** [goveo/react-international-phone#7]
`<PhoneInput 
  onChange={(phone) => {
    setPhoneNumber(phone)
  }}
  initialCountry="ma" 
/>`

i can't set the value to what i want cause it doesn't exist

**Comment by goveo** [comment]
@sadiki-o Hey!

If you want to set the value you can use the `initialPhone` prop.
Seems like there is a typo in the "Basic usage" example.

Let me know if this helped. Thanks!

**Comment by goveo** [comment]
@sadiki-o You can now set the `value` property (after [version 1.4.0](https://github.com/goveo/react-international-phone/releases/tag/v1.4.0) update). Thanks!
