### ISSUE TITLE
Vite module federation error while consuming in host

### ISSUE THREAD

**Issue by raffidahmad** [goveo/react-international-phone#74]
**Describe the bug**
Vite module federation doesn't work, when used in a host project, the following error pops up.

**To Reproduce**

1. Setup vite module federation & expose a simple component for the phone input
2. Consume that component in host
3. Crashes the site

**Expected behavior**
Should not crash site and show the phone input

**Screenshots**

**Desktop (please complete the following information):**

- OS: All
- Browser All
- Version All

**Smartphone (please complete the following information):**

- Device: All
- OS: All
- Browser All
- Version All

**Additional context**
```
__federation_shared_react.js:9 Uncaught TypeError: Cannot read properties of null (reading 'useRef')
    at r.useRef (__federation_shared_react.js:9:6177)
    at e.usePhoneInput (__federation_expose_MuiPhone-1cb13654.js:9:23177)
    at e.PhoneInput (__federation_expose_MuiPhone-1cb13654.js:9:13227)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
```

**Comment by goveo** [comment]
@raffidahmad 
I don't know how the Vite module federation works. Can you provide a reproducible example? (with https://codesandbox.io/ for example)

**Comment by raffidahmad** [comment]
> @raffidahmad I don't know how the Vite module federation works. Can you provide a reproducible example? (with https://codesandbox.io/ for example)

https://codesandbox.io/p/sandbox/clever-taussig-4vd53t

You can see the remote app working but not the host app.
To verify that module federation is working, you can comment the `<PhoneInput />` component in `MuiPhone` directory then run.

1. yarn run build
2. yarn run preview

**Comment by goveo** [comment]
@raffidahmad Can you please check if module federation works correctly with v3.0.1?

I have added the ES6 module to the build and seems like it fixes a problem.

**Comment by raffidahmad** [comment]
@goveo Yes that fixed the module federation issue. However the css needs to be inserted in the host but i guess thats an unrelated issue.
Thank you for the fix.

**Comment by goveo** [comment]
@raffidahmad Awesome!
Consider leaving a star on this repo if you like the project. ⭐ Thanks!
