### ISSUE TITLE
E164 formatted value

### ISSUE THREAD

**Issue by ziemkowski** [goveo/react-international-phone#87]
### Is your feature request related to a problem? Please describe.
When saving the value to a database, we should be storing an E164 value. There doesn't seem to be a way to retrieve such a value. 

We provide an E164 formatted value to the component and should be able to only ever handle E164 values as a consumer of this component.

### Describe the solution you'd like
Ideally the `onChange(phone)` value would be an object with multiple values such as `phone`, `country`, `e164`, `dialCode`, etc. so the subscriber can use object destructuring to get the info they care about, e'.g. `onChange(({ e164, country }) => ...`

Since that would be a breaking change, I imagine it would be opted into via an argument/parameter (and then maybe changed in your next major version?). The nice thing about it though is future additions to that object would no longer be breaking changes.

### Describe alternatives you've considered
I'm not sure if simply stripping non-numeric values is sufficient _(is it?)_. That's what I'm doing now but I'm not sure if there are values I'm not aware of that would fail to validate on the server with Google's libphonenumber when given only digits.

Using something like `awesome-phonenumber` seems like extreme overkill.

### Additional context
One problem with formatting the `onChange` value from the user's side is that it would surely get passed right back into the component which could cause an update loop, which we already see:

As it is today, our E164 `value` instantly triggers an `onChange` on mount. Being able to compare our existing E164 value with the new value would allow us to avoid an update loop while maintaining a database-ready E164 value in our state instead.

### Additional note
Your Storybook has [an e164 page](https://react-international-phone-storybook.vercel.app/?path=/story/phoneinput--e-164-format), but it doesn't seem to make sense or function correctly (and there is no [story source view](https://github.com/storybookjs/storybook/tree/master/addons/storysource) configured). I'm assuming it was meant to show us how to get E164 values?

### P.S.
If the headings in this ticket are easier to read than usual, you may want to update the issue templates to use `###` instead of `**`

**Comment by goveo** [comment]
@ziemkowski Does it necessary to return e164 value exactly on change callback?

Maybe you can just format value to e164 before form submit:
```ts
const toE164 = (phone: string) => {
  return `+${phone.replace(/\D/g, '')}`;
}
```

```tsx
const [phone, setPhone] = useState('+1 ');

return (
  <form onSubmit={(e) => {
    const formValues = {/* some form values */};
    submit({
      ...formValues
      phone: toE164(formValues.phone);
    });
  }}>
    // ...
    <PhoneInput value={phone} onChange={setPhone} />
    // ...
  </form>
);
```

Can you provide a code example if you have some problems with this approach?

**Comment by ziemkowski** [comment]
Cool, that's what I was doing but I wasn't sure if that's all it would take.

However, our approach has to change because while passing in an E164 value works when the dial code is editable it doesn't when the dial code is hidden. For example `+14045555555` correctly becomes `+1 (404) 555-5555` when the dial code is enabled, but when it is not, this value renders as `+14 (140) 455-5555`.

Most Americans are only familiar with the US national format (we _never ever_ use `+` and the `1` is generally only included in toll free and other business numbers). That means a we'd probably see many users deleting the `+1` thinking it is wrong and then starting to enter their national format, which turns into a country code in this input.

For example, we're located in Atlanta, GA, US and our area code is 404. If I select the contents of the field and then start typing `404` it becomes `+40 (4` even though the input was set to US before typing (with country guessing disabled, it shows up at `+4 (04`, which is still not the national format). 

Because of that, in order to be able to use this component (I'm trying everything I can to avoid that russian component), we have to move the dial code out of the text input (using the dial code preview).

Since I can't provide an E164 to the component, what format should work?  The problem is I have to parse previously entered data and I'd also like to have it stored as E164 for future SMS usability.  I'm using `libphonenumber-for-php` to prepare the value given to this component. However, I can't seem to use the national format because of differences in how that library and this component format it in some locations, such as the UK (the php library adds a `0` to the national number [as seen here](https://giggsey.com/libphonenumber/index.php?phonenumber=161+496+0000&country=GB&language=&region=), which results in `+44 0161 496000` rather than the expected `+44 161 496 0000`). 

Any ideas?

Ideally we'd deal with a standardized format both in and out, such as E164 or RFC3966.  To avoid a major breaking change, perhaps something like a `useStandardFormat`, `strictDataFormat`, or `useE164` param? I would expect the new parameter would affect both the parsing of the incoming `value` and the `onChange(phone)` value.

If that's not possible, perhaps treating the issue of the dial code breaking the format when `disableDialCodeAndPrefix` is true as a bug would be enough? Then I could pass libphonenumber's international format to the component regardless of that setting.

**Comment by goveo** [comment]
@ziemkowski Oh, now I see what's wrong.. I slightly missed that use case 😬 

I don't wanna update inner logic for input handling for disabled dial codes.
By the way, I think it current logic is quite valid -> so what string user pass to the `value` prop that is what input should render.

I can propose some workaround for your use case (I need to export some internal functions for that):
```tsx
export const Test = () => {
  const initialPhone = '+14045555555';

  const [country, setCountry] = useState(() => {
    // guessing country of inital phone
    return guessCountryByPartialNumber({ phone: initialPhone }).country;
  });

  const [phone, setPhone] = useState(
    // removing dial code for inital phone
    // '+14045555555' -> '4045555555'
    removeDialCode({
      phone: initialPhone,
      dialCode: country?.dialCode || '',
    }),
  );

  // constructing E164 format from country and phone value
  const e164Phone = country
    ? `+${country.dialCode}${removeNonDigits(phone)}`
    : '';

  return (
    <div>
      <span style={{ color: 'black' }}>E164 phone: {e164Phone}</span>
      <PhoneInput
        value={phone}
        onChange={(phone, country) => {
          setPhone(phone);
          // save country to get ability to construct E164
          setCountry(getCountry({ field: 'iso2', value: country }));
        }}
        // passing country as "defaultCountry"
        defaultCountry={country?.iso2}
        disableDialCodeAndPrefix
      />
    </div>
  );
};
```
![chrome_JNGnRIePrj](https://github.com/goveo/react-international-phone/assets/25800848/6f8a0e81-a85e-4bfd-b8af-571de7e0ba3d)

I can export `guessCountryByPartialNumber`, `removeDialCode` and `getCountry` helper functions if this workaround works for you case.

**Comment by goveo** [comment]
@ziemkowski v3.1.2 is released.
Exported `getCountry`, `guessCountryByPartialPhoneNumber` and `removeDialCode` helper functions.

Didn't have time to write a proper docs for it, but you can use following code as example:
```tsx
import { useState } from "react";
import {
  PhoneInput,
  getCountry,
  guessCountryByPartialPhoneNumber,
  removeDialCode,
} from "react-international-phone";
import "react-international-phone/style.css";

const App = () => {
  const initialPhone = "+14045555555";

  const [country, setCountry] = useState(() => {
    // guessing country of inital phone
    return guessCountryByPartialPhoneNumber({ phone: initialPhone }).country;
  });

  const [phone, setPhone] = useState(
    // removing dial code for inital phone
    // '+14045555555' -> '4045555555'
    removeDialCode({
      phone: initialPhone,
      dialCode: country?.dialCode || "",
    })
  );

  // constructing E164 format from country and phone value
  const e164Phone = country
    ? `+${country.dialCode}${phone.replace(/\D/g, "")}`
    : "";

  return (
    <div style={{ color: "black", fontSize: "13px" }}>
      <span>E164 phone: {e164Phone}</span>
      <PhoneInput
        value={phone}
        onChange={(phone, country) => {
          setPhone(phone);
          // save country to get ability to construct E164
          setCountry(getCountry({ field: "iso2", value: country }));
        }}
        // passing country as "defaultCountry"
        defaultCountry={country?.iso2}
        disableDialCodeAndPrefix
      />
    </div>
  );
};
```

Please give feedback if this solves your problem 🙏

**Comment by ziemkowski** [comment]
@goveo I got E164 round-trip working with these utilities. Thank you! _Slava Ukraini!_
