### ISSUE TITLE
Support multiple mask formats within a country

### ISSUE THREAD

**Issue by ziemkowski** [goveo/react-international-phone#92]
### Is your feature request related to a problem? Please describe.
Many countries have multiple formats, especially between mobile and landline numbers. 

For example: Australian’s expect to see the `... ... ...` [mobile format](https://en.wikipedia.org/wiki/Telephone_numbers_in_Australia#Mobile_phones) (which will also apparently apply to `05` numbers, but not `0550` numbers, soon) for our mobile phone input, and `. .... ....` landline format for the other inputs. The Australian format was changed from mobile to landline in #48, but really _both_ formats need to be supported.

### Describe the solution you’d like
Ideally the input would “just know” based on what has been entered.

For example, you could add a map of regex to mask to the end of the `CountryData` with another type....

```js
['Australia', 'au', '61', '. .... ....', 0, [], {'/^04/': '... ... ...', '/^05(?!50)/': '... ... ...'}],
```

I wonder if the `CountryData` type is getting too convoluted though, and if it might be better to create a new structure with additional formats, and have `parseCountry()` add an `additionalFormats` property to `ParsedCountry` instead, using a new structure in the `countryData.ts` file, like...

```js
export const additionalFormats: AdditionalFormats = {
  au:  {'/^04/': '... ... ...', '/^05(?!50)/': '... ... ...'},
};
```

### Describe alternatives you’ve considered
For our use case, we know if we’re asking for a mobile phone or landline, so for us this would work with a boolean `mobile` attribute on the `<PhoneInput>` component, and there could be a separate mobile format.

I suspect many consumers of the component wouldn’t know (or care) if it’s going to be a mobile or landline number though.  I also suspect some countries have more than two formats available.

Another option might be to take a callback to determine the mask based on the country and number entered so far, but I feel like that's just going to require any multi-national consumer of this component to reinvent the wheel, which shouldn't be needed considering the name of the project.

**Comment by ziemkowski** [comment]
@goveo  That would be great! We're live in production and receiving user reports about it, so the sooner the better.

I'm happy to switch to a specific PR/branch to fix this for our users.

**Comment by goveo** [comment]
@ziemkowski Changes are available in `react-international-phone@next` version. Please check if it's working as expected 🙏

I will probably add more breaking changes to next canary versions, so make sure you locked current version in package.json to avoid unwanted breaking changes updates
```bash
npm i react-international-phone@next --save-exact
```

I will close this issue when this feature will be released in v4

**Comment by goveo** [comment]
@ziemkowski I exported `getCountryMaskFormat` function (and renamed) in `4.0.0-canary.2` version.
Setting data-attribute is not that easy because all formatting logic is inside a hook.

By the way I am thinking about passing object as a second argument for `onChange` callback so current mask format can be passed here in future 🤔

Something like that:
```tsx
<PhoneInput
  onChange={(phone, { formatMask, country, event, e164, ...someParamsHere }) => {})}
/>
```

Or even returning E164 phone as first argument (and receiving e164 as value), so component consumer will get it in state by default..

**Comment by ziemkowski** [comment]
@goveo The idea being that `formatMask` would by the current matched format for the given phone number, so I wouldn't need to use `getCountryMaskFormat`? 

Currently we use the second param to call `getCountry()`, but I assume this would also alleviate that as I imagine `country` in your example is that current parsed country value?  Pretty exciting in that case, especially the possibility of round-trip e164!

**Comment by goveo** [comment]
> The idea being that `formatMask` would be the current matched format for the given phone number, so I wouldn't need to use `getCountryMaskFormat`?

Yep, that's right.

> I assume this would also alleviate that as I imagine country in your example is that current parsed country value?

Yes, passing only iso value in callback was a mistake I think. I wanna pass a parsed country value here

**Comment by goveo** [comment]
@ziemkowski v4.0.0 is released.
E.164 phone format is now supported out of the box (1 argument of `onChange` callback).
You can get an active formatting mask with [`getActiveFormattingMask` helper function](https://react-international-phone.vercel.app/docs/Usage/GetActiveCountryMask) (note that `getCountryMaskFormat` was removed)

Check out the migration document for v4.
https://react-international-phone.vercel.app/docs/Migrations/migrate-to-v4

I will close this issue, feel free to reopen it if anything is wrong.
