### ISSUE TITLE
showDisabledDialCodeAndPrefix and pass the dial code to the input value at the same time

### ISSUE THREAD

**Issue by Shaker-Hamdi** [goveo/react-international-phone#93]
Is there a way to "showDisabledDialCodeAndPrefix" the can access the "dial code" within the "onChange" function?
For example, I don't want to the user to edit the "Dial Code", and yet I need to pass it with the input value on input change.

I tried the "forceDialCode" prop, and while it does what I want, It triggers an "OnChange" event when the input loads, which triggers the validation for the input on the component mount, which is not what I want.

The "showDisabledDialCodeAndPrefix" combined with "disableDialCodeAndPrefix" does exactly what I want "visually", but the "dial code" itself is not getting passed to the value, how can I access it?

**Comment by goveo** [comment]
@Shaker-Hamdi

It's not supported right now (if I understood you correctly).

You can check this workaround for this case: https://github.com/goveo/react-international-phone/issues/87#issuecomment-1690688205

It will be fixed in next major release (I gonna ping you when it will be released)

**Comment by goveo** [comment]
@Shaker-Hamdi v4.0.0 has been released.
E.164 format is now returned in the 1 argument of the `onChange` callback.

I will close this issue, feel free to reopen it if anything is wrong.
