### ISSUE TITLE
unable to import the css file get the error Unable to resolve path to module 'react-international-phone/style.css'.

### ISSUE THREAD

**Issue by hammadiqbal6** [goveo/react-international-phone#97]
I am trying the use the plugin but its not letting me import the css file for the plugin giving the error Unable to resolve path to module 'react-international-phone/style.css'. I am using yarn to add this package

![image](https://github.com/goveo/react-international-phone/assets/35790892/3e14aa70-37c0-499f-b48f-a526090e6984)
 let me know if you need any additional info.

**Comment by goveo** [comment]
@hammadiqbal6
It's not an issue with a library. Seems like you don't have proper loader for css files.
Check solution like this: https://stackoverflow.com/a/49425633

**Comment by hammadiqbal6** [comment]
thanks i'll check it out

**Comment by jessepinuelas** [comment]
@hammadiqbal6 I had to import the css style this way
```
./../../node_modules/react-international-phone/dist/index.css
```
