### ISSUE TITLE
I need the country mask format for force number validation

### ISSUE THREAD

**Issue by matheusmirandaferreira** [goveo/react-international-phone#98]
I use `react-hook-form` and to force the user to enter a correct number, I need the mask format for validation

## Usage example for solution:
```tsx
      <PhoneInput
        defaultCountry="br"
        onChange={(phone, country, mask) => {
          console.log(phone, country, mask);
        }}
      />
```
Is it possible?

**Comment by goveo** [comment]
@matheusmirandaferreira Hey

You can get country mask right now using this workaround:
```ts
onChange={(phone, country) => {
  const format = getCountry({ field: "iso2", value: country }).format
}}
```

NOTE: Ability to get mask from callback argument will be added in next major release.

**Comment by matheusmirandaferreira** [comment]
@goveo Thanks !

**Comment by goveo** [comment]
@matheusmirandaferreira v4.0.0 has been released.
Check out the migration doc:
https://react-international-phone.vercel.app/docs/Migrations/migrate-to-v4

Now you can use `getActiveFormattingMask` helper function:
https://react-international-phone.vercel.app/docs/Usage/GetActiveCountryMask
